name: generate_spec_pdf
on:
  push:
    branches:
      - working_draft
      - main

jobs:
    # The job that will use the container image you just pushed to ghcr.io
    gen_pdf:
        runs-on: ubuntu-latest
        permissions:
          checks: write
        steps:
            - name: Check out repository code
              uses: actions/checkout@v3
            - name: super-step
              shell: sh
              run: |
                ls -laR
                mkdir reports
                python3 main.py
            - name: Test Report
              uses: dorny/test-reporter@v1
              if: success() || failure()    # run this step even if previous step failed
              with:
                name: FOCUS Validations
                path: reports/*.xml         # Path to test results
                reporter: jest-junit        # Format of test results