name: generate_spec_pdf
on:
  push:
    branches:
      - working_draft

jobs:
    # The job that will use the container image you just pushed to ghcr.io
    gen_pdf:
        runs-on: ubuntu-20.04
        container:
            image: pandoc/extra:latest-ubuntu
        steps:
            - name: Check out repository code
              uses: actions/checkout@v3
            - name: super-step
              shell: sh
              run: |
                DEBIAN_FRONTEND=noninteractive apt-get install -y wkhtmltopdf
                ls -laR
                
